### ISSUE TITLE
Footer overlaps website content

### ISSUE THREAD

**Issue by dalekvim** [eneax/eneaxharja.com#131]
On some screens, in particular on laptops, the footer overlaps the website's content:
![image](https://github.com/user-attachments/assets/419754cf-3027-47cc-aa8b-c31b6f15a531)

This issue appears to be caused by the responsive tailwind class `md:h-[calc(100vh-340px)]` in the 'section' component.

**Comment by eneax** [comment]
@dalekvim Thank you for noticing this and letting me know. 
That class was probably a leftover from the website redesign. 

I will make sure to update it in a future patch. Thanks again!
